=== MVV21/ITMO.Course2021-2022/ITMO.Course.XML.HTML.CSS/ITMO.COURSE.XML.HTML.CSS.Labs/xml/lessons_DTD.dtd
<!ELEMENT Lessons (Lesson+)>
<!ELEMENT Lesson (Discipline_title, Instructor, Begin, Number_of_hours, Final_score)> 
<!ELEMENT Discipline_title (#PCDATA)> 
<!ELEMENT Instructor (#PCDATA)> 
<!ELEMENT Begin (#PCDATA)> 
<!ELEMENT Number_of_hours (#PCDATA)>
<!ELEMENT Final_score (#PCDATA)>

=== MVV21/ITMO.Course2021-2022/ITMO.Course.XML.HTML.CSS/ITMO.COURSE.XML.HTML.CSS.Labs/xml/Lessons.xml
<?xml version = "1.0" encoding = "utf-8" ?>
<!DOCTYPE Lessons SYSTEM "lessons_DTD.dtd">

<Lessons>
	<Lesson id = "8">
		<Discipline_title>Технология ADO.NET</Discipline_title>
		<Instructor>Кузьмин К.М.</Instructor>
		<Begin>2022-02-10</Begin>
		<Number_of_hours>(40)</Number_of_hours>
		<Final_score>Зачет</Final_score>
	</Lesson>
	
	<Lesson id = "9">
		<Discipline_title>Разработка Web-приложений с использованием технологии ASP.NET</Discipline_title>
		<Instructor>Смольянинов А.В</Instructor>
		<Begin>2022-03-01</Begin>
		<Number_of_hours>(50)</Number_of_hours>
		<Final_score>Экзамен</Final_score>
	</Lesson>
	
	<Lesson id = "10">
		<Discipline_title>Программирование на Python</Discipline_title>
		<Instructor>Кузьмин К.М.</Instructor>
		<Begin>2022-03-24</Begin>
		<Number_of_hours>(40)</Number_of_hours>
		<Final_score>Зачет</Final_score>
	</Lesson>
</Lessons>
